### ISSUE TITLE
cl-colors2 usage breaking a number of projects?

### ISSUE THREAD

**Issue by pnathan** [pnathan/cl-ansi-text#10] opened 2019-12-31 18:32 UTC
Referencing PR #8 and @xach 's comment https://github.com/pnathan/cl-ansi-text/commit/d9b1ea3fd2f24f22aaf56ebfda0acc775574b746#r36624741

@guicho271828 - FYI.

**Comment by pnathan** [comment] 2019-12-31 18:34
@xach - I don't maintain cl-colors2. What is the specific problem cl-ansi-text introduced - do you have a test run you could link?

**Comment by xach** [comment] 2019-12-31 19:57
It's nothing directly to do with cl-ansi-text. The real problem is that cl-colors2's package name conflicts with the existing cl-colors, and some common dependency graphs now include both cl-colors and cl-colors2. For example, a number of projects' test systems depend on prove, and the projects also use the original cl-colors. When the system is loaded, both cl-colors and cl-colors2 load, causing a conflict.

Prove's dependence on cl-colors2 comes via cl-ansi-text.

I've proposed to cl-colors2 that it rename its package and the systems that require it be updated to use the new name. We'll see how that goes!

**Comment by pnathan** [comment] 2019-12-31 20:47
@xach how much pain is this causing the broader ecosystem right now? If it's sufficiently painful,  I can back out the cl-color2 change provisionally, and then we can restart work from there.

**Comment by xach** [comment] 2019-12-31 21:46
Moderate pain. Some test systems are broken. It's early in the release cycle. I think it's better to fix the root cause in cl-colors2 at the moment. Time may change my priorities...

**Comment by pnathan** [comment] 2019-12-31 21:50
OK. Looks like Cage has worked on addressing it -  - https://notabug.org/cage/cl-colors2/issues/1 

give me a heads up if you need me to apply a change. I have no desire to cause pain to ripple out.

**Comment by pnathan** [comment] 2019-12-31 21:52
I should also note that Prove is apparently somewhat deprecated in favor of Rove - https://github.com/fukamachi/rove

**Comment by xach** [comment] 2020-01-01 17:23
Ok, cl-colors2 now has the package `cl-colors2` and _not_ `cl-colors`. Could you update the usage of cl-colors2 accordingly?

**Comment by pnathan** [comment] 2020-01-01 19:08
@xach - sure thing.

**Comment by xach** [comment] 2020-01-01 21:36
The branch fixes everything for me.

**Comment by xach** [comment] 2020-01-02 01:34
Oh, and it would be great if it was merged to master.

**Comment by pnathan** [comment] 2020-01-02 18:04
@xach  - just to confirm - you mean the PR at https://github.com/pnathan/cl-ansi-text/pull/11 ? FWIW it doesn't work out of the gate in the CI system, since cl-color2's CL-COLORS2 package rename hasn't been pushed to the latest Quicklisp.

Do you plan to release both at the same time? If so, I'll happily merge to master.

**Comment by xach** [comment] 2020-01-02 19:25
I'll release both at the same time.

**Closed** 2020-01-02 19:29 UTC

**Comment by pnathan** [comment] 2020-01-02 19:36
@xach  - you're good to go on my end. Please advise if further issues arise!

**Comment by guicho271828** [comment] 2020-01-03 16:19
thank you @pnathan for cleaning this up --- I could not predict these issues and I feel sorry. thank you for your work @xach too.
